### ISSUE TITLE
TypeError: 'method' object is not subscriptable

### ISSUE THREAD

**Issue by gancao** [BackofenLab/CRISPRidentify#11]
1. Run initial array detection
2. Refine detected arrays
3. Evaluate candidates
Traceback (most recent call last):
  File "CRISPRidentify.py", line 249, in <module>
    run_over_one_file(complete_path_file, folder_result, pickle_folder)
  File "CRISPRidentify.py", line 210, in run_over_one_file
    flag_dev_mode=FLAG_DEVELOPER_MODE)
  File "components/pipeline.py", line 30, in __init__
    self._run_evaluation()
  File "components/pipeline.py", line 60, in _run_evaluation
    flag_dev_mode=self.flag_dev_mode)
  File "components/module_evaluation.py", line 27, in __init__
    self._extract_features_and_evaluate()
  File "components/module_evaluation.py", line 65, in _extract_features_and_eval       uate
    feature_vector = FeatureExtractor(0, crispr_candidate, list_features).extrac       t()[0]
  File "components/components_evaluation.py", line 957, in extract
    self.list_spacers).output()
  File "components/components_evaluation.py", line 782, in __init__
    self._compute_similarity_repeats_spacers()
  File "components/components_evaluation.py", line 824, in _compute_similarity_r       epeats_spacers
    self.similarity_score_repeats = self._compute_similarity_repeats()
  File "components/components_evaluation.py", line 797, in _compute_similarity_r       epeats
    x = kernel_matrix(graphs, r=3, d=4)
  File "components/components_eden.py", line 158, in kernel_matrix
    data_matrix = vectorize(graphs, **opts)
  File "components/components_eden.py", line 136, in vectorize
    return Vectorizer(**opts).transform(graphs)
  File "components/components_eden.py", line 371, in transform
    feature_rows.append(self._transform(graph))
  File "components/components_eden.py", line 459, in _transform
    graph = self._graph_preprocessing(original_graph)
  File "components/components_eden.py", line 447, in _graph_preprocessing
    graph = _edge_to_vertex_transform(original_graph)
  File "components/components_eden.py", line 1005, in _edge_to_vertex_transform
    graph.nodes[n]['node'] = True
TypeError: 'method' object is not subscriptable

**Comment by Alexander-Mitrofanov** [comment]
fixed
